## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file ./poster.sagetex.sage
from sage.all_cmdline import *   # import sage library
## This file (poster.sagetex.sage) was *autogenerated* from poster.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('poster', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.endofdoc()
